title: Tietokannat ja web-ohjelmointi
# subtitle: e.g. Spring 2023
lang: fi # Or fi for Finnish
baseurl: "/materiaali"
url: "https://hy-tikawe.github.io"
# Uncomment to change the theme color:
theme_color: '#cccccc'

remote_theme: ollpu/jekyll-course-theme@v2

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  # Uncomment for Finnish quotes:
  # smart_quotes: rsquo,rsquo,rdquo,rdquo

permalink: /:title/

# If you want a collection of pages for course material:
collections:
  # In Finnish you might want to write e.g. "materiaali:" instead.
  material:
    output: true
    permalink: /:title/

# Uncomment to hide the section submenus in navigation
# for pages other than the current one:
hide_other_section_menus: true

small_code_font: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
